Set-StrictMode -Version Latest
function ConvertTo-HtmlSafe { param([object]$Value) return [System.Security.SecurityElement]::Escape([string]$Value) }
function New-DiscoveryReport { param([System.Collections.IDictionary]$Data,[string]$ReportsRoot)
 $stamp=Get-Date -Format 'yyyy-MM-dd_HHmmss';$dir=Join-Path $ReportsRoot $stamp;$logs=Join-Path $dir 'logs';New-Item -ItemType Directory -Force -Path $logs|Out-Null
 Initialize-DiscoveryLogger (Join-Path $logs 'discovery.log');Write-DiscoveryLog 'ReportGenerator' 'Generating sanitized report.';Write-DiscoveryLog 'SystemInfo' 'Completed local collection.';Write-DiscoveryLog 'NetworkConnections' ('Completed with {0} unique connection(s).' -f @($Data.observedConnections).Count);Write-DiscoveryLog 'OdbcDiscovery' ('Completed with {0} item(s).' -f @($Data.odbc).Count);Write-DiscoveryLog 'DriverDiscovery' ('Completed with {0} item(s).' -f @($Data.databaseDrivers).Count);Write-DiscoveryLog 'ShareDiscovery' ('Completed with {0} item(s).' -f @($Data.networkShares).Count);Write-DiscoveryLog 'ServiceDiscovery' ('Completed with {0} item(s).' -f @($Data.relatedServices).Count);Write-DiscoveryLog 'ConfigDiscovery' ('Completed with {0} sanitized hint(s).' -f @($Data.configurationHints).Count);foreach($warning in @($Data.warnings)){Write-DiscoveryLog 'Collection' $warning 'WARN'}
 $report=[ordered]@{schemaVersion='1.0';agentVersion='0.1.0';generatedAt=(Get-Date).ToString('o');system=$Data.system;selectedApplication=$Data.selectedApplication;network=$Data.network;observedConnections=@($Data.observedConnections);remoteEndpoints=@($Data.remoteEndpoints);odbc=@($Data.odbc);databaseDrivers=@($Data.databaseDrivers);networkShares=@($Data.networkShares);relatedServices=@($Data.relatedServices);configurationHints=@($Data.configurationHints);architectureInference=$Data.architectureInference;warnings=@($Data.warnings);safetyPrivacy='Somente leitura local. Sem dados clínicos, segredos, upload, autenticação ou alteração de sistemas.'}
 $safe=ConvertTo-SafeObject $report;$json=$safe|ConvertTo-Json -Depth 10;(Join-Path $dir 'report.json')|ForEach-Object {[IO.File]::WriteAllText($_,$json,[Text.Encoding]::UTF8)}
 $inf=$safe.architectureInference;$server=if($inf.likelyServer){$inf.likelyServer.hostname+' '+$inf.likelyServer.ip}else{'Não identificado'};$conn=@($safe.observedConnections).Count;$html="<!doctype html><html lang='pt-BR'><meta charset='utf-8'><title>Hexxon Discovery</title><style>body{font:15px Segoe UI,Arial;background:#faf9f7;color:#251b35;margin:40px}h1{color:#35135c}h2{border-bottom:2px solid #d9cdea;padding-bottom:6px}.card{background:white;padding:20px;margin:16px 0;border-radius:8px;box-shadow:0 1px 5px #ddd}pre{white-space:pre-wrap;word-break:break-word}.good{color:#167347}</style><h1>HEXXON Bridge Discovery</h1><p>Relatório técnico local e sanitizado</p><div class='card'><h2>Resumo executivo</h2><p><b>Servidor provável:</b> $(ConvertTo-HtmlSafe $server)<br><b>Confiança:</b> $(ConvertTo-HtmlSafe $inf.confidence)<br><b>Conexões observadas:</b> $conn</p></div><div class='card'><h2>Inferência de arquitetura</h2><p>$(ConvertTo-HtmlSafe $inf.statement)</p><pre>$(ConvertTo-HtmlSafe ($safe.architectureInference|ConvertTo-Json -Depth 6))</pre></div><div class='card'><h2>Dados técnicos</h2><pre>$(ConvertTo-HtmlSafe $json)</pre></div><div class='card'><h2>Segurança e privacidade</h2><p>Somente leitura local. Nenhum dado clínico ou segredo é incluído; nada é enviado à internet.</p></div></html>";[IO.File]::WriteAllText((Join-Path $dir 'report.html'),$html,[Text.Encoding]::UTF8)
 $summary="HEXXON BRIDGE DISCOVERY`r`n=======================`r`n`r`nComputador: $($safe.system.hostname)`r`nAplicação: $($safe.selectedApplication.friendlyName)`r`nServidor provável: $server`r`nConexões observadas: $conn`r`nTecnologias possíveis: $($inf.possibleTechnologies -join ', ')`r`nConfiança: $($inf.confidence)`r`n`r`nPróximo passo recomendado: enviar este ZIP ao responsável técnico para avaliação. `r`n";[IO.File]::WriteAllText((Join-Path $dir 'summary.txt'),$summary,[Text.Encoding]::UTF8)
 Write-DiscoveryLog 'ReportGenerator' 'Report created successfully.';$zip=Join-Path $ReportsRoot ('HexxonDiscoveryReport_'+$stamp+'.zip');Compress-Archive -Path (Join-Path $dir '*') -DestinationPath $zip -Force;return [pscustomobject]@{directory=$dir;zip=$zip}
}
Export-ModuleMember -Function New-DiscoveryReport
