[CmdletBinding()]
param([switch]$Mock)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$moduleRoot = Join-Path $PSScriptRoot 'modules'
@('Logger','PrivacySanitizer','SystemInfo','ProcessDiscovery','NetworkConnections','OdbcDiscovery','DriverDiscovery','ShareDiscovery','ServiceDiscovery','ConfigDiscovery','ArchitectureInference','ReportGenerator') | ForEach-Object { Import-Module (Join-Path $moduleRoot ($_.ToString()+'.psm1')) -Force }
Add-Type -AssemblyName PresentationFramework,PresentationCore,WindowsBase

function Get-MockData {
 $app=[pscustomobject]@{friendlyName='Compulab (simulado)';executableName='Compulab.exe';pid=4242;path='C:\Compulab\Compulab.exe';fileVersion='1.0.0';publisher='Hexxon Demo';productName='Compulab';fileDescription='Aplicação demonstrativa';matchStrength='strong'}
 [ordered]@{system=[pscustomobject]@{hostname='LAB-CLIENTE-DEMO';windowsVersion='Windows 11 (simulado)';architecture='AMD64';powerShellVersion=$PSVersionTable.PSVersion.ToString();accountType='domain';partOfDomain=$true;interfaces=@();machineTime=(Get-Date).ToString('o');timezone='America/Sao_Paulo'};selectedApplication=$app;network=[pscustomobject]@{source='mock'};observedConnections=@([pscustomobject]@{localAddress='192.168.1.25';localPort=51232;remoteAddress='192.168.1.10';remotePort=3050;state='Established';pid=4242;source='mock_observed_tcp_connection'});remoteEndpoints=@([pscustomobject]@{ip='192.168.1.10';hostname='LABSERVER';port=3050;source='mock_observed_tcp_connection';confidence='CONFIRMED'});odbc=@([pscustomobject]@{name='CompulabFirebird';scope='system';driver='Firebird/InterBase(r) driver';settings=[pscustomobject]@{server='LABSERVER';database='COMPULAB';driver='Firebird'};source='mock_local_odbc';confidence='HIGH'});databaseDrivers=@([pscustomobject]@{name='Firebird client library';path='C:\Program Files\Firebird\fbclient.dll';source='mock_local_client_library';confidence='HIGH'});networkShares=@([pscustomobject]@{localPath='Z:';remotePath='\\LABSERVER\COMPULAB';source='mock_existing_smb_mapping';confidence='CONFIRMED'});relatedServices=@();configurationHints=@([pscustomobject]@{configFile='C:\Compulab\config.ini';key='server';value='LABSERVER';source='mock_local_config';confidence='HIGH'});warnings=@()}
}

function Get-LocalStaticData {
 param([object]$Application)
 $script:CollectionWarnings=@()
 function Invoke-LocalCollection { param([string]$Name,[scriptblock]$Action) try { & $Action } catch { $script:CollectionWarnings += "$Name indisponível; a análise continuou."; @() } }
 $system=Invoke-LocalCollection 'Informações do sistema' { Get-DiscoverySystemInfo }
 $odbc=Invoke-LocalCollection 'ODBC' { Get-DiscoveryOdbc }
 $drivers=Invoke-LocalCollection 'Drivers' { Get-DiscoveryDrivers }
 $shares=Invoke-LocalCollection 'Compartilhamentos locais' { Get-DiscoveryShares }
 $services=Invoke-LocalCollection 'Serviços locais' { Get-DiscoveryServices }
 $hints=Invoke-LocalCollection 'Configuração local' { Get-DiscoveryConfigHints $Application }
 [ordered]@{system=$system;selectedApplication=$Application;network=[pscustomobject]@{observation='TCP metadata only'};observedConnections=@();remoteEndpoints=@();odbc=@($odbc);databaseDrivers=@($drivers);networkShares=@($shares);relatedServices=@($services);configurationHints=@($hints);warnings=@($script:CollectionWarnings)}
}

[xml]$xaml=@'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" Title="Hexxon Bridge Discovery" Height="650" Width="820" WindowStartupLocation="CenterScreen" ResizeMode="NoResize" Background="#FAF9F7">
<Grid Margin="42"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
<StackPanel><TextBlock Text="HEXXON" FontSize="26" FontWeight="Bold" Foreground="#35135C"/><TextBlock Text="Bridge Discovery" FontSize="18" Foreground="#5A4A6B"/><Border Height="1" Background="#DED6E8" Margin="0,14,0,16"/></StackPanel>
<Grid Grid.Row="1">
<StackPanel x:Name="WelcomePanel"><TextBlock Text="Vamos identificar como o Compulab se conecta à infraestrutura do laboratório." FontSize="23" TextWrapping="Wrap"/><Border Background="White" Padding="22" Margin="0,25,0,0" CornerRadius="8"><StackPanel><TextBlock Text="✓ Somente leitura" Foreground="#167347" FontSize="16" Margin="0,4"/><TextBlock Text="✓ Nenhum dado enviado à internet" Foreground="#167347" FontSize="16" Margin="0,4"/><TextBlock Text="✓ Nenhum sistema será alterado" Foreground="#167347" FontSize="16" Margin="0,4"/><TextBlock Text="✓ Nenhum dado clínico será coletado" Foreground="#167347" FontSize="16" Margin="0,4"/></StackPanel></Border></StackPanel>
<StackPanel x:Name="OpenPanel" Visibility="Collapsed"><TextBlock Text="1. Abra o Compulab" FontSize="24" FontWeight="SemiBold"/><TextBlock Text="Abra o Compulab normalmente e deixe-o funcionando. Quando estiver pronto, clique em Continuar." FontSize="16" TextWrapping="Wrap" Margin="0,18,0,0"/></StackPanel>
<StackPanel x:Name="SelectPanel" Visibility="Collapsed"><TextBlock Text="2. Selecione o Compulab" FontSize="24" FontWeight="SemiBold"/><TextBlock x:Name="CandidateInfo" Text="Aplicações candidatas encontradas" Margin="0,18,0,8"/><ComboBox x:Name="ProcessBox" Height="58" FontSize="15" DisplayMemberPath="friendlyName"/><TextBlock x:Name="ProcessDetail" TextWrapping="Wrap" Foreground="#5A4A6B" Margin="0,12,0,0"/><Button x:Name="OtherButton" Content="Selecionar outro" Width="160" HorizontalAlignment="Left" Margin="0,18,0,0"/></StackPanel>
<StackPanel x:Name="ObservePanel" Visibility="Collapsed"><TextBlock Text="3. Use o Compulab por um minuto" FontSize="24" FontWeight="SemiBold"/><TextBlock Text="Enquanto analisamos as conexões, use o Compulab normalmente. Se possível: abra um cadastro, consulte uma solicitação, visualize exames ou abra um resultado. Não altere nada que você não faria normalmente." FontSize="16" TextWrapping="Wrap" Margin="0,18,0,0"/><TextBlock x:Name="TimerText" Text="Analisando... 01:00" FontSize="24" Foreground="#35135C" Margin="0,28,0,16"/><StackPanel><TextBlock x:Name="ProcessStatus" Text="• Processo monitorado"/><TextBlock x:Name="ConnectionStatus" Text="• Conexões observadas"/><TextBlock x:Name="StaticStatus" Text="• Configuração local, drivers, ODBC, rede e serviços analisados"/></StackPanel></StackPanel>
<StackPanel x:Name="FinishPanel" Visibility="Collapsed"><TextBlock x:Name="FinishTitle" Text="Análise concluída" FontSize="25" FontWeight="SemiBold" Foreground="#167347"/><TextBlock x:Name="FinishSummary" FontSize="16" TextWrapping="Wrap" Margin="0,18,0,0"/><TextBlock x:Name="ReportMessage" Foreground="#167347" Margin="0,18,0,0" TextWrapping="Wrap"/></StackPanel>
</Grid>
<DockPanel Grid.Row="2" Margin="0,22,0,0"><Button x:Name="HelpButton" Content="Preciso de ajuda" Width="150" DockPanel.Dock="Left"/><StackPanel Orientation="Horizontal" HorizontalAlignment="Right"><Button x:Name="PrimaryButton" Content="Começar" Width="190" Height="42" Background="#35135C" Foreground="White" FontSize="16"/><Button x:Name="SecondaryButton" Content="Finalizar agora" Width="150" Height="42" Margin="12,0,0,0" Visibility="Collapsed"/></StackPanel></DockPanel>
</Grid></Window>
'@
$reader=New-Object System.Xml.XmlNodeReader $xaml;$window=[Windows.Markup.XamlReader]::Load($reader)
$names='WelcomePanel','OpenPanel','SelectPanel','ObservePanel','FinishPanel','CandidateInfo','ProcessBox','ProcessDetail','OtherButton','TimerText','ProcessStatus','ConnectionStatus','StaticStatus','FinishTitle','FinishSummary','ReportMessage','PrimaryButton','SecondaryButton','HelpButton'
foreach($name in $names){Set-Variable -Name $name -Value $window.FindName($name)}
$script:Step='welcome';$script:Candidates=@();$script:Selected=$null;$script:Data=$null;$script:Connections=@();$script:Seconds=60;$script:Timer=$null;$script:Report=$null
function Set-Step { param([string]$Name) foreach($p in @($WelcomePanel,$OpenPanel,$SelectPanel,$ObservePanel,$FinishPanel)){$p.Visibility='Collapsed'};switch($Name){'welcome'{$WelcomePanel.Visibility='Visible';$PrimaryButton.Content='Começar';$SecondaryButton.Visibility='Collapsed'}'open'{$OpenPanel.Visibility='Visible';$PrimaryButton.Content='Continuar';$SecondaryButton.Visibility='Collapsed'}'select'{$SelectPanel.Visibility='Visible';$PrimaryButton.Content='Continuar';$SecondaryButton.Visibility='Collapsed'}'observe'{$ObservePanel.Visibility='Visible';$PrimaryButton.Content='Observando...';$PrimaryButton.IsEnabled=$false;$SecondaryButton.Visibility='Visible'}'finish'{$FinishPanel.Visibility='Visible';$PrimaryButton.Content='Gerar relatório';$PrimaryButton.IsEnabled=$true;$SecondaryButton.Visibility='Collapsed'}'reported'{$FinishPanel.Visibility='Visible';$PrimaryButton.Content='Abrir pasta do relatório';$PrimaryButton.IsEnabled=$true;$SecondaryButton.Visibility='Collapsed'}};$script:Step=$Name }
function Update-ProcessDetail {$p=$ProcessBox.SelectedItem;if($p){$ProcessDetail.Text=("Executável: {0}{4}PID: {1}{4}Caminho: {2}{4}Versão: {3}" -f $p.executableName,$p.pid,$p.path,$p.fileVersion,[Environment]::NewLine)}}
function Complete-Observation {if($script:Timer){$script:Timer.Stop()};$script:Data.observedConnections=@($script:Connections|Sort-Object remoteAddress,remotePort,localAddress,localPort -Unique);$script:Data.remoteEndpoints=Get-RemoteEndpointMetadata $script:Data.observedConnections;$script:Data.architectureInference=Get-ArchitectureInference $script:Data.remoteEndpoints $script:Data.databaseDrivers $script:Data.configurationHints;$inf=$script:Data.architectureInference;$server=if($inf.likelyServer){$inf.likelyServer.hostname+' ('+$inf.likelyServer.ip+')'}else{'Não identificado'};$FinishSummary.Text=("Servidor provável: {0}{6}Possível tecnologia: {1}{6}Conexões observadas: {2}{6}ODBC: {3} configuração(ões) | Compartilhamentos: {4} | Indícios de configuração: {5}{6}Confiança: {7}" -f $server,($inf.possibleTechnologies -join ', '),@($script:Data.observedConnections).Count,@($script:Data.odbc).Count,@($script:Data.networkShares).Count,@($script:Data.configurationHints).Count,[Environment]::NewLine,$inf.confidence);Set-Step 'finish'}
$ProcessBox.Add_SelectionChanged({Update-ProcessDetail})
$OtherButton.Add_Click({$script:Candidates=Get-DiscoveryAllProcesses;$ProcessBox.ItemsSource=$script:Candidates;$CandidateInfo.Text='Selecione manualmente a aplicação em execução.';$ProcessBox.SelectedIndex=0})
$HelpButton.Add_Click({[System.Windows.MessageBox]::Show("1. Feche esta janela.`n2. Não altere nada no servidor.`n3. Gere o relatório parcial, se disponível.`n4. Envie o ZIP ao responsável.",'Preciso de ajuda','OK','Information')|Out-Null})
$SecondaryButton.Add_Click({Complete-Observation})
$PrimaryButton.Add_Click({
 try {switch($script:Step){
  'welcome'{Set-Step 'open'}
  'open'{if($Mock){$script:Candidates=@((Get-MockData).selectedApplication);$CandidateInfo.Text='Aplicação simulada para desenvolvimento.'}else{$script:Candidates=Get-DiscoveryProcesses;if(!$script:Candidates){$script:Candidates=Get-DiscoveryAllProcesses;$CandidateInfo.Text='Nenhuma correspondência forte foi encontrada. Selecione o Compulab na lista.'}else{$CandidateInfo.Text='Aplicações candidatas encontradas'}};$ProcessBox.ItemsSource=$script:Candidates;$ProcessBox.SelectedIndex=0;Set-Step 'select'}
  'select'{$script:Selected=$ProcessBox.SelectedItem;if(!$script:Selected){throw 'Selecione uma aplicação antes de continuar.'};Set-Step 'observe';$script:Connections=@();$script:Seconds=60;if($Mock){$script:Data=Get-MockData}else{$script:Data=Get-LocalStaticData $script:Selected};$ProcessStatus.Text='✓ Processo monitorado';$StaticStatus.Text='✓ Configuração local, drivers, ODBC, rede e serviços analisados';$script:Timer=New-Object Windows.Threading.DispatcherTimer;$script:Timer.Interval=[TimeSpan]::FromSeconds(1);$script:Timer.Add_Tick({if(!$Mock){$script:Connections += @(Get-ProcessConnections $script:Selected.pid)}else{$script:Connections=@($script:Data.observedConnections)};$script:Seconds--; $TimerText.Text=('Analisando... 00:{0:D2}' -f [Math]::Max(0,$script:Seconds));$ConnectionStatus.Text=('✓ Conexões observadas: {0}' -f @($script:Connections|Sort-Object remoteAddress,remotePort -Unique).Count);if($script:Seconds -le 0){Complete-Observation}});$script:Timer.Start()}
  'finish'{$reports=Join-Path $root 'reports';$script:Report=New-DiscoveryReport -Data $script:Data -ReportsRoot $reports;$ReportMessage.Text=("Relatório criado com sucesso.{0}{1}" -f [Environment]::NewLine,$script:Report.zip);Set-Step 'reported'}
  'reported'{if($script:Report){Start-Process -FilePath explorer.exe -ArgumentList @($script:Report.directory)}}
 }} catch {[System.Windows.MessageBox]::Show("Não conseguimos concluir esta etapa automaticamente.`nNada foi alterado.`nVocê pode tentar novamente ou gerar um relatório parcial quando ele estiver disponível.",'Hexxon Discovery','OK','Warning')|Out-Null}
})
Set-Step 'welcome';$window.ShowDialog()|Out-Null
